version: '2.1'
orbs:
  node: circleci/node@5.1.0
workflows:
  auto-attedance:
    jobs:
      - exec-script
jobs:
  exec-script:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: node main.js
          name: Run script
      - store_artifacts:
          path: ./snapshot
