version: '2.1'
workflows:
  auto-attedance:
    jobs:
      - exec-script
jobs:
  exec-script:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: node main.js
          name: Run script
      - store_artifacts:
          path: ./snapshot
