version: '2.1'
orbs:
  node: circleci/node@x.y
workflows:
  auto-attedance:
    jobs:
      - exec-script
jobs:
  exec-script:
    executor: 
      name: node/default
      tag: 16-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          command: node main.js
          name: Run script
      - store_artifacts:
          path: ./snapshot
