name: Auto attedance

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 2'

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run auto attedance
        run: |
          npm ci
          node main.js
        env:
          CI: true
          SPADA_USERNAME: ${{ secrets.SPADAUSERNAME }}
          SPADA_PASSWORD: ${{ secrets.SPADAPASSWORD }}
      - name: Upload snapshot
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: snapshot
